### ISSUE TITLE
OpenCL进行推理，第二次提问，出现segmentfault(coredump)

### ISSUE THREAD

**Issue by orange-island** [wangzhaode/mnn-llm#98]
模型使用的是fp16。
目前手里有两块显卡，一块是NVIDIA 3090 24G，另外一块显卡是国内某厂家显卡（16G，支持OpenCL）。NVIDIA 3090使用cuda，可以成功运行，并多次提问。
问题在于，当使用OpenCL运行时，无论是NVIDIA 3090还是另外一张显卡，在进行第二次提问时，都会挂掉，出现segment fault，程序挂掉。
目前使用的MNN版本，是最新的2.6.0，编译方式如下：
```
# 需要调试，所以使用了Debug 版本，而不是Release版本
cmake -DCMAKE_BUILD_TYPE=Debug -DMNN_OPENCL=ON -DMNN_USE_SYSTEM_LIB=ON -DMNN_SEP_BUILD=OFF ..
```
ChatGLM-MNN的编译方式如下：
```
cmake ..
make -j8
```

例如，第一次提问输入“hello”，回答是“Hello, how can I assist you today?”。
第二次提问输入“nice”，程序挂掉，gdb出现的信息类似于：
```
Cannot access memory at address 0x7f234f1cc148
Cannot access memory at address 0x7f234f1cc140
Failed to read a valid object file image from memory.
Core was generated by `./cli_demo'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f234df82e87 in ?? ()
[Current thread is 1 (LWP 29536)]
(gdb) bt
#0  0x00007f234df82e87 in ?? ()
Backtrace stopped: Cannot access memory at address 0x7ffc854b24a0
```

**Comment by orange-island** [comment]
@wangzhaode 大佬，帮忙看看。
